config/routes.rb
Rails.application.routes.draw do

  get 'dso/echo'

  resources :macs

  get 'time' => 'dso#time'
  get 'sample' => 'dso#sample'
  get 'buzz' => 'dso#buzz'
  get 'client' => 'dso#client'
  post 'client' => 'dso#client'
end

app/models/mac.rb
class Mac < ActiveRecord::Base
end

app/controllers/macs_controller.rb
class MacsController < ApplicationController
  before_action :set_mac, only: [:show, :edit, :update, :destroy]

  # GET /macs
  # GET /macs.json
  def index
    @macs = Mac.all
  end

  # GET /macs/1
  # GET /macs/1.json
  def show
  end

  # GET /macs/new
  def new
    @mac = Mac.new
  end

  # GET /macs/1/edit
  def edit
  end

  # POST /macs
  # POST /macs.json
  def create
    @mac = Mac.new(mac_params)

    respond_to do |format|
      if @mac.save
        format.html { redirect_to @mac, notice: 'Mac was successfully created.' }
        format.json { render :show, status: :created, location: @mac }
      else
        format.html { render :new }
        format.json { render json: @mac.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /macs/1
  # PATCH/PUT /macs/1.json
  def update
    respond_to do |format|
      if @mac.update(mac_params)
        format.html { redirect_to @mac, notice: 'Mac was successfully updated.' }
        format.json { render :show, status: :ok, location: @mac }
      else
        format.html { render :edit }
        format.json { render json: @mac.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /macs/1
  # DELETE /macs/1.json
  def destroy
    @mac.destroy
    respond_to do |format|
      format.html { redirect_to macs_url, notice: 'Mac was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mac
      @mac = Mac.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mac_params
      params.require(:mac).permit(:address)
    end
end

app/helpers/macs_helper.rb
module MacsHelper
end

app/views/macs/_form.html.haml
= form_for @mac do |f|
  - if @mac.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mac.errors.count, "error")} prohibited this mac from being saved:"
      %ul
        - @mac.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :address
    = f.text_area :address
  .actions
    = f.submit 'Save'

app/views/macs/edit.html.haml
%h1 Editing mac

= render 'form'

= link_to 'Show', @mac
\|
= link_to 'Back', macs_path

app/views/macs/index.html.haml
%h1 Listing macs

%table
  %thead
    %tr
      %th Address
      %th
      %th
      %th

  %tbody
    - @macs.each do |mac|
      %tr
        %td= mac.address
        %td= link_to 'Show', mac
        %td= link_to 'Edit', edit_mac_path(mac)
        %td= link_to 'Destroy', mac, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Mac', new_mac_path

app/views/macs/new.html.haml
%h1 New mac

= render 'form'

= link_to 'Back', macs_path

app/views/macs/show.html.haml
%p#notice= notice

%p
  %b Address:
  = @mac.address

= link_to 'Edit', edit_mac_path(@mac)
\|
= link_to 'Back', macs_path